global:
  scrape_interval: 30s
  evaluation_interval: 15s

rule_files:
  - mongoDBAlert.rules
  - web.rules

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: MongoDB
    scrape_timeout: 1m
    scrape_interval: 1m
    static_configs:
      - targets: ['mongoexporter:9216']

  - job_name: Web
    static_configs:
      - targets: ['web:5000']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'